In [3]:
import numpy as np

In [6]:
np.dot([3,4],[5,6])

39

In [10]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [13]:
print("minimum", np.amin([24,47,35,39]))

print("maximum", np.amax([24,47,35,39]))

minimum 24
maximum 47


In [14]:
np.ceil(28.1)

29.0

In [15]:
np.ceil(np.sqrt(np.square(5.5)))

6.0

In [17]:
#help(np) is to call for help

In [18]:
x=np.array([5, 9, 13])
x

array([ 5,  9, 13])

In [19]:
print(x)

[ 5  9 13]


In [21]:
type(x)

numpy.ndarray

In [22]:
#copy array into other
y=np.asarray(x)
print(y)

[ 5  9 13]


In [24]:
z=np.copy(y)
print(z)

[ 5  9 13]


In [25]:
#data type conversion in numpy

np.array((x),dtype=float)

array([ 5.,  9., 13.])

In [27]:
print(y)

[ 5  9 13]


In [28]:
print(x)

[ 5  9 13]


In [31]:
type(x)

numpy.ndarray

In [32]:
x

array([ 5,  9, 13])

In [39]:
matrix_A=[[1,2,3],[4,5,6],[7,8,9]]

In [34]:
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [35]:
x.dtype

dtype('int32')

In [38]:
type(matrix_A)

list

In [41]:
type(matrix_A)

list

In [42]:
A=np.array(matrix_A)

In [43]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
type(A)

numpy.ndarray

In [45]:
A.ndim

2

In [47]:
A.size

9

In [48]:
A.shape

(3, 3)

In [49]:
A.dtype

dtype('int32')

In [56]:
(A, dtype:=float)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 float)

In [57]:
# parametrs of range in python were start, stop and stepsize
# What is the restriction in the python range? Python range cannot generate float data.
# In numpy range, float data can be generated.

list(range(2,5.4, .3))
# we can see below error on the python range in generating float means decimal data

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
a=np.arange(2,5.3,.3)

In [59]:
a

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. ])

In [60]:
#reverse order
a[::-1]

array([5. , 4.7, 4.4, 4.1, 3.8, 3.5, 3.2, 2.9, 2.6, 2.3, 2. ])

In [67]:
print("Every 5h number in reverse order\n",np.arange(50,-1,-5))

Every 5h number in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [68]:
# print("linearly spaced numbers betweeen 10 and 40\n, it is different from range
#print(np.linspace(10,40,num=5), which can be stated as "I want 5 numbers which are equally spaced between 10 and 40.
print(np.linspace(10,40,5))

[10.  17.5 25.  32.5 40. ]


In [70]:
print(np.linspace(10,40,5, retstep=True))

(array([10. , 17.5, 25. , 32.5, 40. ]), 7.5)


# Matrix Creation

In [71]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [74]:
#Creating "NUll Matrix" in numpy
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [75]:
#Creating "Unity Matrix" in numpy
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [80]:
print(5*np.ones((3,3)))

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [83]:
# A matrix has been generated by using two functions, arange of 30 and reshape function has been used to arrange these numbers
# into 5 rows and 6 columns
x= np.arange(30).reshape(5,6)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [87]:
x= np.arange(40).reshape(5,8)
print(x)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


# Random Numbers Generation using

#There are three ways to generate randon numbers:
#np.random.rand
#np.random.randn
#np.random.randint

# rand function for Uniform distribution

In [88]:
#Features of "np.random.rand"
np.random.seed(10)
print("random number generation (from uniform distribution)")
# 1: They will all be +ve numbers, uniformly distributed, and all are between 0 and 1
# 2: The randomness within the rand functions is governed by a parameter of rand function that is called "seed" number.
# 3: For a defined seed numbers in generation of the random numbers every time we run the numbers will rmain same
# 4: If we plot the graph of these random numbers will give us a graph of uniform distribution.
print(np.random.rand(10,6))

[[0.49691604 0.00974039 0.20245833 0.46238122 0.79512025 0.63679784]
 [0.42854872 0.97874837 0.01911582 0.22753903 0.42511501 0.72150166]
 [0.67579431 0.53502732 0.95088202 0.20040244 0.2350568  0.83038229]
 [0.60033194 0.55079756 0.05135285 0.52152899 0.33271307 0.6636503 ]
 [0.56510161 0.97565417 0.86681102 0.63577454 0.08397592 0.79037621]
 [0.07089637 0.58483372 0.60194671 0.27929259 0.24616143 0.63083265]
 [0.91564334 0.25824674 0.62851002 0.72461895 0.66985126 0.56093864]
 [0.70446331 0.57845798 0.81928787 0.19909659 0.02880615 0.513699  ]
 [0.38504667 0.6402109  0.50989087 0.99714635 0.93681752 0.94946717]
 [0.82296013 0.23134325 0.34265742 0.94712401 0.11258844 0.61708018]]


In [91]:
#Features of "np.random.rand"
np.random.seed(5)
print("random number generation (from uniform distribution)")
# 1: They will all be +ve numbers, uniformly distributed, and all are between 0 and 1
# 2: The randomness within the rand functions is governed by a parameter of rand function that is called "seed" number.
print(np.random.rand(10,6))

random number generation (from uniform distribution)
[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  0.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 0.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 0.57766286]
 [0.00164217 0.51547261 0.63979518 0.9856244  0.2590976  0.80249689]
 [0.87048309 0.92274961 0.00221421 0.46948837 0.98146874 0.3989448 ]
 [0.81373248 0.5464565  0.77085409 0.48493107 0.02911156 0.08652569]
 [0.11145381 0.25124511 0.96491529 0.63176605 0.8166602  0.566082  ]]


In [93]:
#Features of "np.random.rand"
np.random.seed(5)
print("random number generation (from uniform distribution)")
# 3: For a defined seed numbers in generation of the random numbers every time we run the numbers will rmain same
# Here (5,3) represent a matrix of 5 rows and 3 columns, if you compare the number from above for the same seem number
#you will clearly see that numbers for the same seed have not changed only the matrix size has changed.
print(np.random.rand(5,3)) 

random number generation (from uniform distribution)
[[0.22199317 0.87073231 0.20671916]
 [0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005 ]
 [0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703]]


# randn function for normal distribution

In [89]:
#Features of "np.random.randn"
print("random number generation (from normal distribution with mean of Zero and standard deviation of 1)")
# 1: They will be +ve or -ve numbers, normally distributed between -1 and 1.
# 2: This does not need any seed number
# 3: If we plot the graph of these random numbers will give us a graph of normal distribution.
print(np.random.randn(10,6))

random number generation (from normal distribution with mean of Zero and standard deviation of 1)
[[ 0.24126297 -1.59895539 -0.37195129  1.0887945  -0.02014361  1.27132924]
 [-3.43334441  1.42276913 -0.46427635  0.77342064  1.11116799 -0.61884593]
 [ 1.39337457  0.99570039  0.95526441 -0.28967271 -1.17827199 -0.21112738]
 [-0.44601423  0.64077877 -1.57944592 -2.09257196  0.30224568 -0.08581292]
 [ 0.22832378 -0.19245437 -0.49593949 -0.66339941  0.18308509  0.42716938]
 [-1.19135461 -0.95295469  0.50844826 -0.37823236  0.41453097 -0.61852285]
 [ 0.11678245 -0.99665765  0.25287203  1.15395084 -0.79665059 -0.96341037]
 [ 0.12388873  0.87570114  0.15337361 -0.33779921 -0.26228857  0.96973857]
 [ 0.73516293  1.30886302  1.19408867 -1.55343849 -0.59113424 -1.32821901]
 [ 0.62293345  1.55578752 -0.47873526  0.10782958  1.44215657  0.45987875]]


# randint function
# 1: rand function generate +ve numbers between 0 and 1.
# 2: randn function generate both +ve and -ve numbers between -1 and +1. 
# 3: So in order to generate integers we need a functions knows as "randint"

In [99]:
a=np.random.randint(10,1000,10) # it will generate randomly an array of 10 numbers within a range of starting from 10 ending on 999, 
print("Random integer vector :", a)
type(a)

Random integer vector : [933 935 811 739 863 401 538 104  24 996]


numpy.ndarray

In [108]:
#using randint we can generate a matrix that will only have integers

# Question here arise that I given a range from 1 to 10000 but how it determines the number of elements in matrix
# Answer: by the size of or rank of the matrix means the number of elements should be 6x7=42"

A= np.random.randint(1,10000,(6,7)) 
print(A)


[[ 921 6849 6410 6465 7785 4264 3781]
 [7920 4562 1573 4211 1112 5190 7421]
 [ 915  291 1055 3662 5730 4979 6174]
 [3842 8275 6165  234 2689 5027 9423]
 [9652 8267 5574 3067 5456 1206 5551]
 [ 155  598 1242 6903 6714 8422 5522]]


# Real life example of randint function in generation of OTP program

In [109]:
from numpy.random import randint as ri

In [112]:
def generate_otp():
    otp1=ri(1000,10000,1)
    print("your OTP is ", otp1)
    user_otp = int(input("Enter OTP"))
    if otp1 == user_otp:
        print("login success")
    else:
        print("Invalid OTP, Generate new OTP")

generate_otp()

your OTP is  [2137]


Enter OTP 2137


login success


# Sorting

In [117]:
M= ri(1,100,25).reshape(5,5)
print("\n 5x5 Matrix of random integers\n", '-'*50, '\n', M)
print("\n here is the way to sort a matrix along each row\n", '-'*50, "\n", np.sort(M, axis=1)) # by default numpy sorts matrix on rows so axis not needed
print("\n here is the way to sort a matrix along each column\n", '-'*50, "\n", np.sort(M, axis=0))


 5x5 Matrix of random integers
 -------------------------------------------------- 
 [[82 68 80 18 88]
 [12 31 27  9 52]
 [62 85 53 75 26]
 [10 32 40 60 23]
 [81 59 45 16 16]]

 here is the way to sort a matrix along each row
 -------------------------------------------------- 
 [[18 68 80 82 88]
 [ 9 12 27 31 52]
 [26 53 62 75 85]
 [10 23 32 40 60]
 [16 16 45 59 81]]

 here is the way to sort a matrix along each column
 -------------------------------------------------- 
 [[10 31 27  9 16]
 [12 32 40 16 23]
 [62 59 45 18 26]
 [81 68 53 60 52]
 [82 85 80 75 88]]


In [121]:
print('Minimum = ', M.min(), 'and Maximum = ', M.max())

Minimum =  9 and Maximum =  88


# numpy condition

In [123]:
salary = ri(8,70,10)
salary

array([59, 29, 57, 24, 40, 34, 38, 38, 37, 58])

In [127]:
print(np.where(salary<40)) # It generates the indicies of the location of numbers in the array but we want real data so see below

(array([1, 3, 5, 6, 7, 8], dtype=int64),)


In [128]:
salary[np.where(salary<40)]

array([29, 24, 34, 38, 38, 37])

In [129]:
salary

array([59, 29, 57, 24, 40, 34, 38, 38, 37, 58])

# Clip function is used to round up or down to minimum or maximum values of the elements of the array respectively.

In [131]:
# All values below 30 will be set to 30 and above 60 will be set to 60.

np.clip(salary,a_min=30, a_max=60)

array([59, 30, 57, 30, 40, 34, 38, 38, 37, 58])

Indexing and Slicing

In [134]:
c=np.arange(10,40)
print(c)
print(type(c))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]
<class 'numpy.ndarray'>


In [137]:
print("array list of elements on the listed indicies [5, 9, 15] are :", c[[5, 9, 15]])

array list of elements on the listed indicies [5, 9, 15] are : [15 19 25]


In [25]:
B = np.arange(1,10,1).reshape(3,3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [171]:
print(B[1][2])

6


In [158]:
print(B[2])

[7 8 9]


In [159]:
print(B[1])

[4 5 6]


In [168]:
print(B[1:2,1:2])

[[5]]


In [174]:
print(B[1:3,1:3])

[[5 6]
 [8 9]]


In [176]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
print(B[:,1:3])

[[2 3]
 [5 6]
 [8 9]]


In [178]:
print(B[0:2,1:2])

[[2]
 [5]]


# updating matrix element

In [179]:
print(B[0:3,2:3])

[[3]
 [6]
 [9]]


In [182]:
print(B[2,2])

9


In [183]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
print(B[1,1])

5


In [186]:
print(B[1])

[4 5 6]


In [187]:
B[1]=10
print(B)

[[ 1  2  3]
 [10 10 10]
 [ 7  8  9]]


In [188]:
B[:,2]=15
print(B)

[[ 1  2 15]
 [10 10 15]
 [ 7  8 15]]


In [189]:
np.where(B==8)

(array([2], dtype=int64), array([1], dtype=int64))

In [191]:
print(B[2,1])

8


In [192]:
B[2,1]=20
print(B)

[[ 1  2 15]
 [10 10 15]
 [ 7 20 15]]


In [2]:
import numpy as np

In [7]:
M=np.arange(1,10,1).reshape(3,3)
print(M)
type(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [12]:
print(M[1,1:2])

[5]


In [22]:
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print(M[1:2,2:3])

[[6]]


In [36]:
C=np.arange(1,10).reshape(3,3)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
D=np.random.randint(20,30,(3,3))
print(D)

[[24 20 21]
 [20 25 22]
 [21 25 21]]


In [33]:
np.sort(D)

array([[20, 21, 24],
       [20, 22, 25],
       [21, 21, 25]])

In [34]:
np.sort(D,axis=0)

array([[20, 20, 21],
       [21, 25, 21],
       [24, 25, 22]])

In [40]:
E=np.arange(50,41,-1).reshape(3,3)
print(E)

[[50 49 48]
 [47 46 45]
 [44 43 42]]


In [41]:
np.sort(E)

array([[48, 49, 50],
       [45, 46, 47],
       [42, 43, 44]])

In [42]:
np.sort(E,axis=0)

array([[44, 43, 42],
       [47, 46, 45],
       [50, 49, 48]])

# Sub-setting

In [1]:
import numpy as np

In [2]:
from numpy.random import randint as ri

In [3]:
F = np.array(ri(10,100,15)).reshape(5,3)
print(F)

[[56 85 28]
 [24 32 86]
 [86 22 34]
 [85 43 67]
 [86 20 92]]


In [48]:
F>50

array([[False,  True,  True],
       [ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [49]:
F[F>50]

array([90, 63, 70, 93, 62, 51, 96, 91, 69, 78])

In [4]:
np.count_nonzero(F)

15

In [ ]:
Lecture completed 11 May 2024

#LECTURE DATE 12/05/2024

Universal Functions

In [5]:
import numpy as np

In [8]:
from numpy.random import randint as ri

In [10]:
mat1=np.array(ri(1,10,9).reshape(3,3))

In [12]:
mat2=np.array(ri(11,20,9).reshape(3,3))

In [15]:
print(mat1+mat2)

[[14 19 23]
 [21 23 20]
 [25 25 20]]


In [16]:
mat1

array([[3, 6, 6],
       [7, 9, 8],
       [6, 9, 5]])

In [17]:
mat2

array([[11, 13, 17],
       [14, 14, 12],
       [19, 16, 15]])

In [18]:
mat1+mat2

array([[14, 19, 23],
       [21, 23, 20],
       [25, 25, 20]])

In [20]:
mat3=np.array(ri(11,20,6).reshape(2,3))

In [21]:
mat3

array([[19, 18, 18],
       [19, 15, 11]])

In [25]:
mat1

array([[3, 6, 6],
       [7, 9, 8],
       [6, 9, 5]])

In [26]:
mat3

array([[19, 18, 18],
       [19, 15, 11]])

In [27]:
mat1*mat2

array([[ 33,  78, 102],
       [ 98, 126,  96],
       [114, 144,  75]])

In [32]:
Z=np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [40]:
O=np.array([[1,1,1]])

In [41]:
O

array([[1, 1, 1]])

In [42]:
print(O)

[[1 1 1]]


In [45]:
print(Z + O)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [46]:
print(Z + O.T)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
